dist: trusty

language: java
jdk:
  - oraclejdk8


branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script: "mvn clean package"

notifications:
  email:
    recipients:
      - pearlismylove@gmail.com


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-deploy
    region: ap-southeast-1
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: pearlismylove/spring-boot-cd
      branch: master