language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script: "mvn clean build"

notifications:
  email:
    recipients:
      - pearlismylove@gmail.com
      